services:
  mongo:
    image: mongo:8
    container_name: mongo-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - gallery-network

  garage:
    image: dxflrs/garage:v2.3.0
    container_name: garage
    restart: unless-stopped
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"
    environment:
      RUST_LOG: info
    volumes:
      - ./garage/config/garage.toml:/etc/garage.toml:ro
      - garage_data:/var/lib/garage
    networks:
      - gallery-network

  mongodb-exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: mongodb-exporter
    restart: unless-stopped
    command:
      - --collect-all
      - --compatible-mode
    environment:
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017
    ports:
      - "9216:9216"
    depends_on:
      - mongo
    networks:
      - gallery-network

  gallery:
    container_name: gallery-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MONGO_URI=${MONGO_URI}
        - GARAGE_ENDPOINT=${GARAGE_ENDPOINT}
        - GARAGE_ACCESS_KEY=${GARAGE_ACCESS_KEY}
        - GARAGE_SECRET_KEY=${GARAGE_SECRET_KEY}
        - GARAGE_BUCKET=${GARAGE_BUCKET}
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - GARAGE_ENDPOINT=${GARAGE_ENDPOINT}
      - GARAGE_ACCESS_KEY=${GARAGE_ACCESS_KEY}
      - GARAGE_SECRET_KEY=${GARAGE_SECRET_KEY}
      - GARAGE_BUCKET=${GARAGE_BUCKET}
    depends_on:
      - mongo
      - garage
    networks:
      - gallery-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=15d"
      - "--web.enable-lifecycle"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - gallery-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/grafana.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    ports:
      - "3001:3000"
    networks:
      - gallery-network

volumes:
  mongo_data:
  garage_data:
  prometheus_data:
  grafana_data:

networks:
  gallery-network:
    driver: bridge
