services:
  mongo:
    image: mongo:8
    container_name: mongo-db
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

    volumes:
      - mongo_data:/data/db

    networks:
      - gallery-network

  garage:
    image: dxflrs/garage:v2.3.0
    container_name: garage
    restart: unless-stopped

    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"

    environment:
      RUST_LOG: info

    volumes:
      - ./garage/config/garage.toml:/etc/garage.toml:ro
      - garage_data:/var/lib/garage

    networks:
      - gallery-network

volumes:
  mongo_data:
  garage_data:

networks:
  gallery-network:
    driver: bridge
