/**
 * Comprehensive label set for CLIP zero-shot image tagging.
 *
 * Covers animals (specific species), food, fashion, culture, geography,
 * nature, places, and objects — no hardcoded domain restrictions.
 * Add labels here to support new domains without changing any other code.
 */
export const LABELS: string[] = [
  // ── Specific animals ──────────────────────────────────────────────────────
  "tiger", "white tiger", "lion", "leopard", "cheetah", "jaguar", "puma", "lynx", "cougar",
  "panda", "red panda", "polar bear", "brown bear", "grizzly bear", "black bear",
  "wolf", "coyote", "jackal", "hyena",
  "fox", "fennec fox", "arctic fox", "red fox",
  "dog", "puppy", "cat", "kitten", "rabbit", "hare",
  "deer", "elk", "moose", "reindeer", "gazelle", "antelope", "ibex",
  "zebra", "horse", "donkey", "mule",
  "giraffe", "elephant", "rhinoceros", "hippopotamus", "camel", "alpaca", "llama",
  "gorilla", "chimpanzee", "orangutan", "baboon", "monkey", "lemur",
  "kangaroo", "koala", "wombat", "platypus",
  "penguin", "eagle", "hawk", "falcon", "owl", "parrot", "macaw",
  "flamingo", "toucan", "peacock", "swan", "pelican", "seagull", "crow", "pigeon",
  "snake", "python", "cobra", "crocodile", "alligator", "lizard", "iguana", "gecko",
  "turtle", "tortoise", "frog",
  "shark", "whale", "dolphin", "seal", "walrus", "otter", "sea lion",
  "octopus", "jellyfish", "crab", "lobster",
  "goldfish", "clownfish", "tropical fish",
  "butterfly", "bee", "dragonfly", "ant", "spider",
  "wildlife", "animal", "bird", "reptile", "insect",

  // ── Food ─────────────────────────────────────────────────────────────────
  "pizza", "burger", "hamburger", "cheeseburger", "hot dog", "sandwich", "wrap",
  "taco", "burrito", "quesadilla", "nachos",
  "sushi", "sashimi", "ramen", "udon", "miso soup", "tempura", "onigiri",
  "pasta", "spaghetti", "lasagna", "gnocchi", "risotto", "ravioli",
  "rice", "fried rice", "paella", "biryani", "pilaf",
  "bread", "baguette", "croissant", "bagel", "toast", "pita",
  "waffle", "pancake", "crepe",
  "donut", "cake", "cupcake", "pie", "tart", "cheesecake",
  "ice cream", "gelato", "sorbet",
  "chocolate", "candy", "cookie", "brownie", "macaron",
  "french fries", "chips", "popcorn",
  "salad", "caesar salad", "greek salad",
  "soup", "stew", "curry", "dal", "tagine", "couscous",
  "steak", "grilled chicken", "fried chicken", "roast chicken", "barbecue",
  "grilled fish", "shrimp", "seafood",
  "egg", "omelette", "scrambled eggs", "fried egg",
  "cheese", "butter", "yogurt",
  "coffee", "espresso", "latte", "cappuccino", "tea",
  "juice", "smoothie", "milkshake",
  "wine", "beer", "cocktail", "champagne",
  "fruit", "apple", "banana", "orange", "strawberry", "grapes",
  "watermelon", "mango", "pineapple", "avocado",
  "vegetables", "broccoli", "carrot", "corn", "tomato", "pepper",
  "food", "dish", "meal", "breakfast", "lunch", "dinner", "dessert", "snack", "street food",

  // ── Fashion & clothing ────────────────────────────────────────────────────
  "shirt", "t-shirt", "blouse", "polo shirt", "button-up shirt",
  "sweater", "pullover", "cardigan", "hoodie", "sweatshirt",
  "jacket", "leather jacket", "denim jacket", "bomber jacket",
  "coat", "overcoat", "trench coat", "raincoat", "winter coat",
  "blazer", "suit", "tuxedo", "business suit",
  "dress", "evening gown", "cocktail dress", "sundress", "maxi dress",
  "skirt", "mini skirt", "pleated skirt", "pencil skirt", "midi skirt",
  "pants", "trousers", "jeans", "denim jeans", "chinos", "sweatpants",
  "shorts", "bermuda shorts",
  "leggings", "tights", "stockings",
  "socks", "ankle socks",
  "shoes", "sneakers", "boots", "ankle boots", "heels", "high heels",
  "sandals", "loafers", "oxford shoes", "running shoes",
  "hat", "cap", "baseball cap", "beanie", "beret", "fedora", "sun hat",
  "scarf", "tie", "bow tie", "gloves", "mittens", "belt",
  "bag", "handbag", "purse", "clutch", "backpack", "tote bag",
  "sunglasses", "glasses", "watch",
  "jewelry", "necklace", "bracelet", "ring", "earrings",
  "uniform", "sportswear", "activewear", "swimsuit", "bikini",
  "traditional dress", "kimono", "sari", "kaftan", "djellaba", "abaya", "hijab",
  "fashion", "clothing", "outfit", "wardrobe", "style",

  // ── Culture, geography & history ─────────────────────────────────────────
  "moroccan", "algerian", "tunisian", "libyan", "egyptian",
  "arabic", "middle eastern", "persian", "turkish", "ottoman",
  "greek", "roman", "byzantine", "ancient",
  "italian", "french", "spanish", "portuguese",
  "chinese", "japanese", "korean", "vietnamese", "thai",
  "indian", "hindu", "buddhist",
  "african", "west african", "east african", "north african",
  "aztec", "mayan", "inca", "native american",
  "viking", "celtic", "medieval", "renaissance",
  "traditional", "cultural", "folk", "ethnic", "indigenous",
  "ceremonial", "ritual", "festival", "carnival", "parade",
  "wedding", "celebration",
  "flag", "coat of arms", "symbol",
  "mosque", "minaret", "church", "cathedral", "temple", "shrine", "synagogue",
  "palace", "castle", "fortress", "citadel", "ruins",
  "pyramid", "sphinx", "colosseum", "acropolis", "parthenon",
  "monument", "statue", "sculpture", "obelisk",
  "market", "bazaar", "souk", "medina",
  "village", "countryside", "rural",

  // ── Nature & landscapes ───────────────────────────────────────────────────
  "mountain", "volcano", "glacier", "iceberg", "hill", "valley",
  "canyon", "gorge", "cliff", "rock formation",
  "waterfall", "river", "lake", "pond", "stream",
  "ocean", "sea", "bay", "coast", "beach", "shoreline",
  "desert", "dunes", "oasis", "savanna", "grassland", "plains",
  "forest", "rainforest", "jungle", "woodland",
  "meadow", "field", "farm", "orchard", "vineyard",
  "garden", "park", "botanical garden",
  "sky", "clouds", "sunrise", "sunset", "night sky", "stars",
  "snow", "ice", "fog", "rain", "storm",
  "grass", "trees", "flowers", "moss", "coral reef",
  "nature", "landscape", "scenery", "environment",

  // ── Places & architecture ─────────────────────────────────────────────────
  "city", "skyline", "downtown", "urban", "suburban",
  "building", "skyscraper", "tower", "apartment", "house", "villa",
  "bridge", "dam", "road", "highway", "railway",
  "airport", "train station", "port", "harbor",
  "museum", "library", "university", "school",
  "hospital", "restaurant", "cafe", "bar", "hotel",
  "shop", "mall", "store", "supermarket",
  "stadium", "arena", "theater", "cinema",
  "street", "alley", "square", "plaza",
  "interior", "room", "kitchen", "bedroom", "living room", "bathroom",
  "office", "workshop", "factory",

  // ── People & activities ───────────────────────────────────────────────────
  "person", "man", "woman", "child", "baby", "elderly person",
  "portrait", "selfie", "family", "couple", "crowd", "group",
  "sports", "football", "soccer", "basketball", "tennis", "swimming",
  "running", "cycling", "hiking", "skiing", "surfing",
  "yoga", "gym", "workout", "exercise",
  "cooking", "baking", "eating",
  "reading", "writing", "painting", "drawing", "photography",
  "music", "concert", "dancing", "singing",
  "travel", "tourism", "adventure", "exploration",
  "graduation", "ceremony",

  // ── Objects & technology ──────────────────────────────────────────────────
  "car", "truck", "motorcycle", "bicycle", "bus", "train", "airplane", "boat",
  "computer", "laptop", "phone", "smartphone", "tablet", "camera",
  "television", "speaker", "headphones",
  "book", "newspaper", "magazine",
  "furniture", "chair", "table", "sofa", "bed",
  "art", "painting", "drawing", "graffiti", "mural",
  "weapon", "sword", "shield", "armor",
  "money", "coins", "banknotes",
  "toy", "game", "board game",
  "candle", "lantern", "lamp",
  "flower", "rose", "sunflower", "tulip", "orchid",
  "tree", "palm tree", "pine tree", "oak tree",
];
