global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "garage"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["garage:3902"]

  - job_name: "gallery-app"
    metrics_path: "/api/metrics"
    static_configs:
      - targets: ["gallery-app:3000"]
  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb-exporter:9216"]
