name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    name: lint, type-check & docker check
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: install dependencies
        run: npm ci

      - name: run eslint
        run: npm run lint

      - name: type check
        run: npm run type-check

      - name: build docker image
        run: |
          docker build \
            --build-arg MONGO_URI="${{ secrets.MONGO_URI }}" \
            --build-arg GARAGE_ENDPOINT="${{ secrets.GARAGE_ENDPOINT }}" \
            --build-arg GARAGE_ACCESS_KEY="${{ secrets.GARAGE_ACCESS_KEY }}" \
            --build-arg GARAGE_SECRET_KEY="${{ secrets.GARAGE_SECRET_KEY }}" \
            --build-arg GARAGE_BUCKET="${{ secrets.GARAGE_BUCKET }}" \
            -t gallery:test .
