name: Continious Integration

on:
  push:
    branches:
      main
  pull_request: 
    branches: 
      main
permissions: 
  contents: read
jobs:
  test-and-build:
    name: lint, build & docker check
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: setup node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: run eslint
        run: pnpm lint

      - name: type check
        run: pnpm type-check

      - name: build next.js
        run: pnpm build

      - name: build docker image
        run: docker build -t gallery:test
